name: Anatomy
on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths:
            - "src/"
jobs:
    print_message:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Hello World"
