name: Anatomy
on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths:
            - "src/**"
    pull_request: 
        branches: ["main"]
        types: ["opened","synchronize","reopened"]
jobs:
    print_message:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Hello World"
    variables:
        runs-on: ubuntu-slim
        env: 
            NAME: ${{ vars.REPO_NAME }}
            APP_ENV: "DEV"
        steps:
            - run: echo $NAME
            - run: |
                echo "printing env variables"
                echo ${{ env.APP_ENV.REQUIRED }}
