name: Anatomy
on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths:
            - "src/**"
    pull_request: 
        branches: ["main"]
        types: ["opened","synchronize","reopened"]
env: 
    NAME: ${{ vars.REPO_NAME }}
    APP_ENV: "DEV"
    REPORT_REQUIRED: True
jobs:
    print_message:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Hello World"
    variables:
        runs-on: ubuntu-slim
        environment: DEV
        env: 
            NAME: ${{ vars.REPO_NAME }}
            APP_ENV: "DEV"
        steps:
            - run: |
                echo $NAME
                echo "printing env variables"
                echo ${{ vars.REQUIRED }}
                echo "Report required "
                echo $REPORT_REQUIRED