name: Artifacts upload and download
on: [push, pull_request,workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-slim
        steps:
            - uses: actions/checkout@v4
            - run: |
                mkdir -p out
                echo "build ${{github.sha}}" > out/build_info.txt
            - uses: actions/upload-artifact@v4
              with:
                name: build-output
                path: out/
    
    deploy:
        runs-on: ubuntu-slim
        needs: build
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: build-output
                path: downloaded/
            - run: |
                cat downloaded/build_info.txt
    
    build-multiple:
        runs-on: ubuntu-slim
        steps:
            - run: |
                mkdir -p out
                echo "build 1" > out/buil1.txt
                echo "build 2" > out/buil2.txt
                echo "build 3" > out/buil3.txt

            - uses: actions/upload-artifact@v4
              with:
                name: build-output-multiple
                path: out/
            - uses: actions/download-artifact@v4
              with: 
                name: build-output-multiple
                path: downloaded/
    
    upload-options:
        runs-on: ubuntu-slim
        steps:
            #- uses: actions/checkout@v4
            - run: |
                mkdir -p out
                echo "build" > out/build_info.txt
            - uses: actions/upload-artifact@v4
              with:
                name: upoad-options
                path: out1/
                if-no-files-found: WARNING
                retention-days: 1 # override the default 90 days
                compression-level: 0 # 0 to 9
                overwrite: false
                include-hidden-files: true #.coverage files


