name: cache
on: [push,pull_request,workflow_dispatch]
jobs:
    package-basic:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
            - name: node setup
              uses: actions/setup-node@v4
              with:
                version: 20
            - name: cache npm packages
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{runner.os}}node-${{hashFiles('node_modules/package-lock.json')}}
            - run: npm ci
            - run: npm test
