name: Expressions
on: [push,pull_request]
jobs:
    test:
        runs-on: ubuntu-slim
        steps:
            - if: github.ref == 'refs/head/main'
              run: echo "Running code from main branch"
            
            - if: github.event_name != 'pull_request'
              run: echo "This is direct commit"

            - if: github.run_attempt > 1
              run: echo "This is attempt ${{github.run_attempt}}"