name: Matrix Strategy
on: [push, pull_request, workflow_dispatch]
jobs:
    strategy-fail-fast:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                node: [18,20,22]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node}}
            - run: npm ci
            - run: npm test


    strategy-basic:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                env: ["Dev", "Stage", "Prod"]
                region: ["us-east-1","us-east-2"]
        steps:
            - name: Deployment
              run: echo "Deploying into region ${{ matrix.region }} into environment ${{ matrix.env }}"
    
    strategy-include:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                env: ["Dev", "Stage", "Prod"]
                region: ["us-east-1","us-east-2"]
                include:
                    - env: "Pre-Prod"
                      region: "us-east-3"
        steps:
            - name: Deployment
              run: echo "Deploying into region ${{ matrix.region }} into environment ${{ matrix.env }}"
    
    strategy-exclude:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                env: ["Dev", "Stage", "Prod"]
                region: ["us-east-1","us-east-2"]
                exclude:
                    - env: "Dev"
        steps:
            - name: Deployment
              run: echo "Deploying into region ${{ matrix.region }} into environment ${{ matrix.env }}"